title: NordicSoft
author: Antolii Zhezliko
title: nordicsoft
email: hello@nordicsoft.ee
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.


baseurl: ""
permalink: /:title/

show_excerpts: false # set to true to show excerpts on the homepage

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - team.html
 - contact.html
 - services.html
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-multiple-languages-plugin

 # jekyll-multiple-languages-plugin settings:
languages: ["en", "et"]
exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]